using System.Collections.Generic;
using System.IO;

namespace tana_gh.UnityDotG.Editor
{
    public class CodeGenContext
    {
        private static string DefaultAutoGeneratedFolder { get; } = "Assets/UnityDotG/AutoGenerated";

        private string _autoGeneratedFolder = "";
        public string AutoGeneratedFolder
        {
            get => string.IsNullOrEmpty(_autoGeneratedFolder) ? DefaultAutoGeneratedFolder : _autoGeneratedFolder;
            set => _autoGeneratedFolder = value;
        }

        internal List<(string path, string content)> PathAndContents { get; } = new();

        public void AddCode(string fileName, string content)
        {
            PathAndContents.Add((GetPath(fileName), content));
        }

        private string GetPath(string fileName)
        {
            return Path.Combine(AutoGeneratedFolder, fileName);
        }
    }
}
