using System.Collections.Generic;
using System.IO;

namespace tana_gh.UnityDotG.Editor
{
    public class CodeGenContext
    {
        private static readonly string defaultAutoGeneratedFolder = "Assets/UnityDotG/AutoGenerated";

        private string autoGeneratedFolder = "";
        public string AutoGeneratedFolder
        {
            get => string.IsNullOrEmpty(autoGeneratedFolder) ? defaultAutoGeneratedFolder : autoGeneratedFolder;
            set => autoGeneratedFolder = value;
        }

        internal readonly List<(string path, string content)> pathAndContents = new();

        public void AddCode(string fileName, string content)
        {
            pathAndContents.Add((GetPath(fileName), content));
        }

        private string GetPath(string fileName)
        {
            return Path.Combine(AutoGeneratedFolder, fileName);
        }
    }
}
