// <auto-generated/>
// This file is generated by UnityDotG. Do not modify it manually.

using UnityEngine;

namespace tana_gh.UnityDotG.Examples
{
    public class ExampleBehaviour : MonoBehaviour
    {
        private void Start()
        {
            Debug.Log("This message is auto-generated with type tana_gh.UnityDotG.Examples.ExampleGenerator.");
        }
    }
}
